# Generated by Django 6.0.6 on 2026-07-15 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('deluxe', 'Deluxe Room'), ('executive', 'executive suite'), ('presidential', 'presidential suite'), ('single', 'Single Room'), ('double', 'Double Room')], max_length=20, unique=True)),
                ('price_per_night', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('description', models.TextField(blank=True, null=True)),
                ('capacity', models.PositiveBigIntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('RoomType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelmanagementapp.roomtype')),
            ],
        ),
    ]
