# Generated by Django 6.0.6 on 2026-07-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagementapp', '0002_rename_roomtype_booking_room_type_booking_booked_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(choices=[('deluxe', 'Deluxe Room'), ('executive', 'Executive Suite'), ('presidential', 'Presidential Suite'), ('single', 'Single Room'), ('double', 'Double Room')], max_length=20, unique=True),
        ),
    ]
